version: '3.7'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - /data:/data
    environment:
      MINIO_ACCESS_KEY: minioAdmin
      MINIO_SECRET_KEY: minioAdmin
    command: server /data

  media_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080-8084:8080'
    links:
      - minio
    restart: always
  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7070:7070"
    depends_on:
      - minio
